### ISSUE TITLE
Viewing a starred link removes it and does not put it in the archive.

### ISSUE THREAD

**Issue by jmk520** [jobbogamer/linkbucket#60]
Steps to reproduce:
1. Click a starred link
2. Return to the "starred" page

Expected results:
The link should still be there to click again.

Actual results:
The link is no longer there, as if it was on the main page and transferred to the archive. However, it also does not appear in the archive.

Version:
2.1.4

Reproducability:
The issue occurs every time.

**Comment by jobbogamer** [comment]
Clicking a starred link incorrectly sets that link's `archived` property to `True`, which means it won't show up on the starred page. It also doesn't show up on the archive page because `starred` is still set to `True` as well.
